name: rscm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.22
  - pandas>=1.5
  - matplotlib>=3.5
  - scikit-learn>=1.1
  - scipy>=1.8
  - jupyter>=1.0
  - jupyterlab>=3.0
  - gcc_linux-64
  - gxx_linux-64
  - make
  - pip
  - pip:
    - nbconvert>=6.0
